[build]
  command = "npm install"
  publish = "."
  functions = "functions"

[[redirects]]
  from = "/xoso"
  to = "/.netlify/functions/api/xoso"
  status = 200

[[redirects]]
  from = "/thoitiet"
  to = "/.netlify/functions/api/thoitiet"
  status = 200

# ğŸ  ThÃªm route /home
[[redirects]]
  from = "/home"
  to = "/.netlify/functions/api/home"
  status = 200
